export const categorySeeds = [
  {
  name: 'Wedding & Events',
  slug: 'wedding-events',
  description: 'Complete wedding planning, Shaadi, Mehndi, Barat & Walima services.',
  icon: 'Heart',
  image: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 1,
  subcategories: [
  { name: 'Shaadi', slug: 'shaadi' },
  { name: 'Mehndi', slug: 'mehndi' },
  { name: 'Barat', slug: 'barat' },
  { name: 'Walima', slug: 'walima' },
  { name: 'Engagement', slug: 'engagement' },
  { name: 'Nikkah', slug: 'nikkah' },
  ],
  filters: [
  { key: 'event-size', label: 'Event Size', type: 'select', options: ['Small (up to 100)', 'Medium (100-300)', 'Large (300-700)', 'Grand (700+)'] },
  ],
  },
  {
  name: 'Catering & Food',
  slug: 'catering-food',
  description: 'Desi, BBQ and Continental catering for every occasion.',
  icon: 'Utensils',
  image: 'https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 2,
  subcategories: [
  { name: 'Desi Food', slug: 'desi-food' },
  { name: 'BBQ', slug: 'bbq' },
  { name: 'Continental', slug: 'continental' },
  { name: 'Desserts & Sweets', slug: 'desserts-sweets' },
  { name: 'Live Food Stations', slug: 'live-food-stations' },
  ],
  filters: [
  { key: 'cuisine', label: 'Cuisine', type: 'multiselect', options: ['Desi', 'BBQ', 'Continental', 'Sindhi', 'Punjabi'] },
  { key: 'pricing', label: 'Pricing', type: 'select', options: ['Budget', 'Mid-Range', 'Premium'] },
  ],
  },
  {
  name: 'Photography & Videography',
  slug: 'photography-videography',
  description: 'Candid wedding photography and cinematic videography.',
  icon: 'Camera',
  image: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 3,
  subcategories: [
  { name: 'Wedding Photography', slug: 'wedding-photography' },
  { name: 'Candid Photography', slug: 'candid-photography' },
  { name: 'Cinematic Videography', slug: 'cinematic-videography' },
  { name: 'Drone Coverage', slug: 'drone-coverage' },
  { name: 'Pre-Wedding Shoot', slug: 'pre-wedding-shoot' },
  ],
  filters: [
  { key: 'coverage-type', label: 'Coverage', type: 'multiselect', options: ['Photography', 'Videography', 'Drone', 'Pre-Wedding'] },
  ],
  },
  {
  name: 'Decoration & Styling',
  slug: 'decoration-styling',
  description: 'Stages, floral decor, lighting and themed event styling.',
  icon: 'Flower',
  image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 4,
  subcategories: [
  { name: 'Stage Decoration', slug: 'stage-decoration' },
  { name: 'Floral Decor', slug: 'floral-decor' },
  { name: 'Lighting & Sound', slug: 'lighting-sound' },
  { name: 'Theme Styling', slug: 'theme-styling' },
  { name: 'Entry Gates', slug: 'entry-gates' },
  ],
  filters: [
  { key: 'theme', label: 'Theme', type: 'multiselect', options: ['Floral', 'Royal', 'Pastel', 'Rustic', 'Modern'] },
  ],
  },
  {
  name: 'Venues & Halls',
  slug: 'venues-halls',
  description: 'Banquet halls, farmhouses and outdoor venues in Sukkur.',
  icon: 'Building2',
  image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 5,
  subcategories: [
  { name: 'Banquet Halls', slug: 'banquet-halls' },
  { name: 'Farmhouses', slug: 'farmhouses' },
  { name: 'Marquee / Lawn', slug: 'marquee-lawn' },
  { name: 'Outdoor Venues', slug: 'outdoor-venues' },
  ],
  filters: [
  { key: 'venue-type', label: 'Venue Type', type: 'select', options: ['Indoor Hall', 'Outdoor Lawn', 'Marquee', 'Farmhouse'] },
  { key: 'capacity', label: 'Capacity', type: 'select', options: ['Up to 200', '200-500', '500-1000', '1000+'] },
  ],
  },
  {
  name: 'Invitation & Stationery',
  slug: 'invitation-stationery',
  description: 'Custom wedding cards, printed & digital invitations.',
  icon: 'Mail',
  image: '',
  sortOrder: 6,
  subcategories: [
  { name: 'Printed Invitations', slug: 'printed-invitations' },
  { name: 'Digital E-Cards', slug: 'digital-e-cards' },
  { name: 'Custom Stationery', slug: 'custom-stationery' },
  ],
  filters: [],
  },
  {
  name: 'Music & Entertainment',
  slug: 'music-entertainment',
  description: 'Live bands, Dhol, DJs and Mehndi choreography.',
  icon: 'Music',
  image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 7,
  subcategories: [
  { name: 'Live Bands', slug: 'live-bands' },
  { name: 'DJ Services', slug: 'dj-services' },
  { name: 'Dhol Players', slug: 'dhol-players' },
  { name: 'Mehndi Dancers', slug: 'mehndi-dancers' },
  ],
  filters: [
  { key: 'entertainment-type', label: 'Type', type: 'multiselect', options: ['Live Band', 'DJ', 'Dhol', 'Dancers'] },
  ],
  },
  {
  name: 'Transport & Bridal Cars',
  slug: 'transport-bridal-cars',
  description: 'Luxury bridal cars and guest transport.',
  icon: 'Car',
  image: '',
  sortOrder: 8,
  subcategories: [
  { name: 'Bridal Cars', slug: 'bridal-cars' },
  { name: 'Coach Hire', slug: 'coach-hire' },
  { name: 'Car Decoration', slug: 'car-decoration' },
  ],
  filters: [],
  },
  {
  name: 'Beauty & Makeup',
  slug: 'beauty-makeup',
  description: 'Bridal makeup, dress designing and grooming.',
  icon: 'Sparkles',
  image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?q=80&w=1600&auto=format&fit=crop',
  sortOrder: 9,
  subcategories: [
  { name: 'Bridal Makeup', slug: 'bridal-makeup' },
  { name: 'Dress Designing', slug: 'dress-designing' },
  { name: 'Mehndi Artist', slug: 'mehndi-artist' },
  { name: 'Hair Styling', slug: 'hair-styling' },
  ],
  filters: [
  { key: 'service-type', label: 'Service', type: 'multiselect', options: ['Makeup', 'Hair', 'Mehndi', 'Dress'] },
  ],
  },
  {
  name: 'Other Services',
  slug: 'other-services',
  description: 'Chairs, tents, gift packs and every other event need.',
  icon: 'MoreHorizontal',
  image: '',
  sortOrder: 10,
  subcategories: [
  { name: 'Chairs & Tents', slug: 'chairs-tents' },
  { name: 'Gift Packs', slug: 'gift-packs' },
  { name: 'Fog & FX', slug: 'fog-fx' },
  ],
  filters: [],
  },
];